/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as LivreurRouteImport } from './routes/livreur'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as AntiDiabeteRouteImport } from './routes/anti-diabete'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivreurIndexRouteImport } from './routes/livreur.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as LivreurBilanRouteImport } from './routes/livreur.bilan'
import { Route as ApiPublicHooksWeeklyReportRouteImport } from './routes/api/public/hooks/weekly-report'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurRoute = LivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiDiabeteRoute = AntiDiabeteRouteImport.update({
  id: '/anti-diabete',
  path: '/anti-diabete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurIndexRoute = LivreurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LivreurRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurBilanRoute = LivreurBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => LivreurRoute,
} as any)
const ApiPublicHooksWeeklyReportRoute =
  ApiPublicHooksWeeklyReportRouteImport.update({
    id: '/api/public/hooks/weekly-report',
    path: '/api/public/hooks/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anti-diabete': typeof AntiDiabeteRoute
  '/diagnostic': typeof DiagnosticRoute
  '/livreur': typeof LivreurRouteWithChildren
  '/thank-you': typeof ThankYouRoute
  '/livreur/bilan': typeof LivreurBilanRoute
  '/product/$slug': typeof ProductSlugRoute
  '/livreur/': typeof LivreurIndexRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anti-diabete': typeof AntiDiabeteRoute
  '/diagnostic': typeof DiagnosticRoute
  '/thank-you': typeof ThankYouRoute
  '/livreur/bilan': typeof LivreurBilanRoute
  '/product/$slug': typeof ProductSlugRoute
  '/livreur': typeof LivreurIndexRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anti-diabete': typeof AntiDiabeteRoute
  '/diagnostic': typeof DiagnosticRoute
  '/livreur': typeof LivreurRouteWithChildren
  '/thank-you': typeof ThankYouRoute
  '/livreur/bilan': typeof LivreurBilanRoute
  '/product/$slug': typeof ProductSlugRoute
  '/livreur/': typeof LivreurIndexRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anti-diabete'
    | '/diagnostic'
    | '/livreur'
    | '/thank-you'
    | '/livreur/bilan'
    | '/product/$slug'
    | '/livreur/'
    | '/api/public/hooks/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anti-diabete'
    | '/diagnostic'
    | '/thank-you'
    | '/livreur/bilan'
    | '/product/$slug'
    | '/livreur'
    | '/api/public/hooks/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anti-diabete'
    | '/diagnostic'
    | '/livreur'
    | '/thank-you'
    | '/livreur/bilan'
    | '/product/$slug'
    | '/livreur/'
    | '/api/public/hooks/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AntiDiabeteRoute: typeof AntiDiabeteRoute
  DiagnosticRoute: typeof DiagnosticRoute
  LivreurRoute: typeof LivreurRouteWithChildren
  ThankYouRoute: typeof ThankYouRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicHooksWeeklyReportRoute: typeof ApiPublicHooksWeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur': {
      id: '/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof LivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-diabete': {
      id: '/anti-diabete'
      path: '/anti-diabete'
      fullPath: '/anti-diabete'
      preLoaderRoute: typeof AntiDiabeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur/': {
      id: '/livreur/'
      path: '/'
      fullPath: '/livreur/'
      preLoaderRoute: typeof LivreurIndexRouteImport
      parentRoute: typeof LivreurRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur/bilan': {
      id: '/livreur/bilan'
      path: '/bilan'
      fullPath: '/livreur/bilan'
      preLoaderRoute: typeof LivreurBilanRouteImport
      parentRoute: typeof LivreurRoute
    }
    '/api/public/hooks/weekly-report': {
      id: '/api/public/hooks/weekly-report'
      path: '/api/public/hooks/weekly-report'
      fullPath: '/api/public/hooks/weekly-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LivreurRouteChildren {
  LivreurBilanRoute: typeof LivreurBilanRoute
  LivreurIndexRoute: typeof LivreurIndexRoute
}

const LivreurRouteChildren: LivreurRouteChildren = {
  LivreurBilanRoute: LivreurBilanRoute,
  LivreurIndexRoute: LivreurIndexRoute,
}

const LivreurRouteWithChildren =
  LivreurRoute._addFileChildren(LivreurRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AntiDiabeteRoute: AntiDiabeteRoute,
  DiagnosticRoute: DiagnosticRoute,
  LivreurRoute: LivreurRouteWithChildren,
  ThankYouRoute: ThankYouRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicHooksWeeklyReportRoute: ApiPublicHooksWeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
